config/routes.rb
Rails.application.routes.draw do

  root "home#index"
  patch :update_comment, to: 'tickets#update_comment'

  resources :tickets do
    member do
      patch :move #Drag js
    end
  end

  resources :scenarios do
    resources :results
  end

  resources :paragraphs do
    resources :sub_paragraphs
    member do
      patch :move #Drag js
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/paragraph.rb
class Paragraph < ApplicationRecord

  before_create :set_position

  acts_as_list
  has_rich_text :content

  has_many :sub_paragraphs, inverse_of: :paragraph, dependent: :destroy
  accepts_nested_attributes_for :sub_paragraphs, reject_if: :all_blank, allow_destroy: true

  scope :ordered_by_position, -> { order(position: :asc) }

  validates :title, presence: true

  def set_position
    self.position = Paragraph.all.count + 1
  end

end

app/models/result.rb
class Result < ApplicationRecord

  belongs_to :scenario, optional: true

  enum dev: { empty: 0, success: 1, failure: 2, untested: 3, comment: 4 }, _prefix: :dev
  enum staging: { empty: 0, success: 1, failure: 2, untested: 3, comment: 4 }, _prefix: :staging

end

app/models/scenario.rb
class Scenario < ApplicationRecord

  has_many :results, inverse_of: :scenario, dependent: :destroy
  belongs_to :ticket

  accepts_nested_attributes_for :results, reject_if: :all_blank, allow_destroy: true

  validates :description, presence: true

end

app/models/sub_paragraph.rb
class SubParagraph < ApplicationRecord

  belongs_to :paragraph, optional: true

  has_rich_text :content

  validates :title, presence: true

end

app/models/ticket.rb
class Ticket < ApplicationRecord

  before_create :set_position

  acts_as_list

  has_many :scenarios
  has_many :results, :through => :scenarios

  scope :ordered_by_position, -> { order(position: :asc) }

  enum tracker: [ :anomaly, :evolution, :assistance, :user_story ]

  validates :issue_id, :title, presence: true
  validates :url_link, presence: true , url: true

  def set_position
    self.position = Ticket.all.count + 1 # Temporaire, ensuite sera delivery_report.tickets.count
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/paragraphs_controller.rb
class ParagraphsController < ApplicationController

  before_action :set_paragraph, only: [:edit, :update, :destroy, :move]

  def index
    @paragraphs = Paragraph.all
    @paragraph = Paragraph.new
  end

  def new
    @paragraph = Paragraph.new
    @paragraph.sub_paragraphs.build
  end

  def create
    @paragraph = Paragraph.create(paragraph_params)
    respond_to do |format|
      if @paragraph.save
        format.html { redirect_to paragraphs_path, notice: "Le paragraphe a été créé avec succès" }
        format.js
      else
        format.html { redirect_to paragraphs_path, notice: "Le paragraphe n'a pas pu être créé" }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @paragraph.update(paragraph_params)
        format.html { redirect_to paragraphs_path, notice: "Le paragraphe a été mis à jour" }
        format.js
      else
        format.html { redirect_to paragraphs_path, notice: "Le paragraphe n'a pas pu être mis à jour" }
      end
    end
  end

  def move
    @paragraph.insert_at(params[:position].to_i)
    head :ok
  end

  def destroy
    @paragraph.destroy
    respond_to do |format|
      format.html {redirect_to paragraphs_path, notice: "Le paragraphe a bien été supprimé"}
      format.js
    end
  end

  private

    def set_paragraph
      @paragraph = Paragraph.find(params[:id])
    end

    def paragraph_params
      params.require(:paragraph).permit(:title, :content, :position, sub_paragraphs_attributes: [:id, :title, :content, :position, :paragraph_id, :_destroy])
    end

end

app/controllers/scenarios_controller.rb
class ScenariosController < ApplicationController

  before_action :set_scenario, only: [:edit, :update, :destroy]

  def index
    @ticket = Ticket.find(params[:ticket_id])
    @scenarios = @ticket.scenarios
  end

  def new
    @scenario = Scenario.new(ticket_id: params[:ticket_id])
    @scenario.results.build
  end

  def create
    @scenario = Scenario.create(scenario_params)
    respond_to do |format|
      if @scenario.save
        format.html {redirect_to scenarios_path(ticket_id: @scenario.ticket_id), notice: "Scénario créé"}
        format.js
      else
        format.html {redirect_to scenarios_path(ticket_id: @scenario.ticket_id), notice: "Scénario non créé"}
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @scenario.update(scenario_params)
        format.html {redirect_to scenarios_path(ticket_id: @scenario.ticket_id), notice: "Scénario mis à jour"}
      else
        format.html {render :new}
      end
    end
  end

  def destroy
    @scenario.destroy
    respond_to do |format|
      format.html {redirect_to scenarios_path(ticket_id: params[:ticket_id]), notice: "Scénario supprimé"}
      format.js
    end
  end

  private

    def set_scenario
      @scenario = Scenario.find(params[:id])
    end

    def scenario_params
      params.require(:scenario).permit(:description, :ticket_id, results_attributes: [:id, :description, :dev, :staging, :scenario_id, :_destroy])
    end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  before_action :set_ticket, only: [:show, :edit, :update, :destroy, :move]

  def index
    @tickets = Ticket.all
    @ticket = Ticket.new
  end

  def show
  end

  def new
    @ticket = Ticket.new
  end

  def create
    @ticket = Ticket.create(test_params)
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: "Successfully created a ticket" }
        format.js
      else
        format.html { render :new, notice: "Successfully created a test" }
        format.js
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @ticket.update(test_params)
        format.html { redirect_to @ticket, notice: "Successfully updated test" }
        format.json { render :show, status: :ok, location: @ticket}
      else
        format.html { render :new, notice: "Successfully created a test" }
        format.json { render json: @ticket.errors}
      end
    end
  end

  def update_comment # Update le commentaire directement dans les tests du ticket
    @ticket = Ticket.find(params[:ticket_id])
    respond_to do |format|
      if @ticket.update(test_params)
        format.html { redirect_to scenarios_path(params[:scenario_id], ticket_id: @ticket.id), notice: "Commentaire mis à jour" }
      else
        format.html { redirect_to @scenario, notice: "Le commentaire n'a pas été mis à jour" }
      end
    end
  end

  def destroy
    @ticket.destroy
    redirect_to tickets_path, notice: "Successfully destroyed a test"
  end

  def move
    @ticket.insert_at(params[:position].to_i)
    head :ok
  end

  private

    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    def test_params
      params.require(:ticket).permit(:tracker, :title, :issue_id, :reference,
                                     :url_link, :position, :description, :comment)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def toastr_flash
    flash.each_with_object([]) do |(type, message), flash_messages|
      type = 'success' if type == 'notice'
      type = 'error' if type == 'alert'
      text = "<script>toastr.#{type}('#{message}', '', { closeButton: true, progressBar: true })</script>"
      flash_messages << text.html_safe if message
    end.join("\n").html_safe
  end
=begin
  def link_to_add_row(name, f, association, **args)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.simple_fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize, f: builder)
    end
    link_to(name, '#', class: "add_fields" + args[:class], data: {id: id, fields: fields.gsub("\n", "")})
  end
=end
end

app/helpers/functionnal_tests_helper.rb
module FunctionnalTestsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/base/_control_sidebar.html.erb
<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
  <!-- Control sidebar content goes here -->
  <div class="p-3">
    <h5>Title</h5>
    <p>Sidebar content</p>
  </div>
</aside>
<!-- /.control-sidebar -->

app/views/base/_footer.html.erb
<!-- Main Footer -->
<footer class="main-footer">
  <!-- To the right -->
  <div class="float-right d-none d-sm-inline">
    Anything you want
  </div>
  <!-- Default to the left -->
  <strong>Copyright &copy; 2014-2019 <a href="https://adminlte.io">AdminLTE.io</a>.</strong> All rights reserved.
</footer>

app/views/base/_header.html.erb
<!-- Navbar -->
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbar links -->
  <ul class="navbar-nav">
    <li class="nav-item">
      <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="index3.html" class="nav-link">Home</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
      <a href="#" class="nav-link">Contact</a>
    </li>
  </ul>

  <!-- SEARCH FORM -->
  <form class="form-inline ml-3">
    <div class="input-group input-group-sm">
      <input class="form-control form-control-navbar" type="search" placeholder="Search" aria-label="Search">
      <div class="input-group-append">
        <button class="btn btn-navbar" type="submit">
          <i class="fas fa-search"></i>
        </button>
      </div>
    </div>
  </form>

  <!-- Right navbar links -->
  <ul class="navbar-nav ml-auto">
    <!-- Messages Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-comments"></i>
        <span class="badge badge-danger navbar-badge">3</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="dist/img/user1-128x128.jpg" alt="User Avatar" class="img-size-50 mr-3 img-circle">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Brad Diesel
                <span class="float-right text-sm text-danger"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">Call me whenever you can...</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="dist/img/user8-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                John Pierce
                <span class="float-right text-sm text-muted"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">I got your message bro</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <!-- Message Start -->
          <div class="media">
            <img src="dist/img/user3-128x128.jpg" alt="User Avatar" class="img-size-50 img-circle mr-3">
            <div class="media-body">
              <h3 class="dropdown-item-title">
                Nora Silvester
                <span class="float-right text-sm text-warning"><i class="fas fa-star"></i></span>
              </h3>
              <p class="text-sm">The subject goes here</p>
              <p class="text-sm text-muted"><i class="far fa-clock mr-1"></i> 4 Hours Ago</p>
            </div>
          </div>
          <!-- Message End -->
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Messages</a>
      </div>
    </li>
    <!-- Notifications Dropdown Menu -->
    <li class="nav-item dropdown">
      <a class="nav-link" data-toggle="dropdown" href="#">
        <i class="far fa-bell"></i>
        <span class="badge badge-warning navbar-badge">15</span>
      </a>
      <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
        <span class="dropdown-header">15 Notifications</span>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-envelope mr-2"></i> 4 new messages
          <span class="float-right text-muted text-sm">3 mins</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-users mr-2"></i> 8 friend requests
          <span class="float-right text-muted text-sm">12 hours</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item">
          <i class="fas fa-file mr-2"></i> 3 new reports
          <span class="float-right text-muted text-sm">2 days</span>
        </a>
        <div class="dropdown-divider"></div>
        <a href="#" class="dropdown-item dropdown-footer">See All Notifications</a>
      </div>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-widget="control-sidebar" data-slide="true" href="#" role="button"><i
          class="fas fa-th-large"></i></a>
    </li>
  </ul>
</nav>
<!-- /.navbar -->

app/views/base/_sidebar.html.erb
<!-- Main Sidebar Container -->
<aside class="main-sidebar sidebar-dark-primary elevation-4">
  <!-- Brand Logo -->
  <a href="index3.html" class="brand-link">
    <span class="brand-text font-weight-light">ProjectsManagement</span>
  </a>

  <!-- Sidebar -->
  <div class="sidebar">
    <!-- Sidebar user panel (optional) -->
    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      <div class="info">
        <a href="#" class="d-block">Toto Létrico</a>
      </div>
    </div>

    <!-- Sidebar Menu -->
    <nav class="mt-2">
      <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
        <!-- Add icons to the links using the .nav-icon class
             with font-awesome or any other icon font library -->
        <li class="nav-item has-treeview menu-open">
          <a href="#" class="nav-link active">
            <i class="nav-icon fas fa-tachometer-alt"></i>
            <p>
              Starter Pages
              <i class="right fas fa-angle-left"></i>
            </p>
          </a>
          <ul class="nav nav-treeview">
            <li class="nav-item">
              <%= link_to "Tickets", tickets_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "Paragraphes", paragraphs_path, class: "nav-link" %>
            </li>
          </ul>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">
            <i class="nav-icon fas fa-th"></i>
            <p>
              Simple Link
              <span class="right badge badge-danger">New</span>
            </p>
          </a>
        </li>
      </ul>
    </nav>
    <!-- /.sidebar-menu -->
  </div>
  <!-- /.sidebar -->
</aside>

app/views/functionnal_tests/edit.html.erb
<h1>Edition de <%= @test.title %> / <%= @test.id %></h1>

<%= simple_form_for @test, wrapper: :horizontal_form do |f| %>

  <%= f.input :tracker, collection: FunctionnalTest.trackers.keys, include_blank: false %>
  <%= f.input :title %>
  <%= f.input :tracker_number %>
  <%= f.input :reference %>
  <%= f.input :url_link %>
  <%= f.input :position %>
  <%= f.input :description %>

  <%= f.button :submit, "Modifier", class: "btn-primary" %>

<% end %>

app/views/functionnal_tests/new.html.erb
<h1>Création d'un test</h1>

<%= simple_form_for @test, wrapper: :horizontal_form do |f| %>

  <%= f.input :tracker, collection: FunctionnalTest.trackers.keys, include_blank: false %>
  <%= f.input :title %>
  <%= f.input :tracker_number %>
  <%= f.input :reference %>
  <%= f.input :url_link %>
  <%= f.input :position %>
  <%= f.input :description %>

  <%= f.button :submit, "Créer", class: "btn-primary" %>

<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar fixed-top navbar-icon-top navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="fas fa-home"></i>
          Home
          </a>
      </li>
      <li class="nav-item <%= 'active' if params[:controller] == 'paragraphs' %>">
        <%= link_to paragraphs_path, class: "nav-link" do %>
          <i class="fas fa-envelope"></i>
          Paragraphes
        <% end %>
      </li>

      <li class=" nav-item <%= 'active' if params[:controller] == 'tickets' %>">
        <%= link_to tickets_path, class: "nav-link" do %>
          <i class="fas fa-envelope"></i>
          Tickets
        <% end %>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-envelope"></i>
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
    <ul class="navbar-nav ">
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="fas fa-bell"></i>
          Test
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">
          <i class="fas fa-globe"></i>
          Test
        </a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projectsmanagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper">
      <%= render "base/header" %>
      <%= render "base/sidebar" %>
      <div class="content-wrapper">
        <%= toastr_flash %>
        <%= yield %>
      </div>
      <%= render "base/footer" %>
      <%= render "base/control_sidebar" %>
    </div>
  </body>
</html>

app/views/paragraphs/_paragraph.html.erb
<!-- Default box -->
<div class="card to_delete" data-id="<%= paragraph.id %>" id="paragraph_<%= paragraph.id %>" >

  <div class="card-header">
    <i class="fas fa-grip-vertical grip text-secondary float-left"></i>
    <b><%= paragraph.title %></b>
    <span>
      <%= link_to edit_paragraph_path(paragraph.id), remote: true, class: "btn btn-tool float-right" do %>
        <i class="fas fa-edit"></i>
      <% end %>
    </span>
    <span class="delete">
      <%= link_to paragraph_path(paragraph.id), method: :delete, data: {confirm: "Etes-vous sur", remote: true }, class: "btn btn-tool float-right" do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </span>
  </div>

  <div class="card-body">
    <%= paragraph.content %>
    <% paragraph.sub_paragraphs.each do |sub_para| %>
      <div class="card">
        <div class="card-header">
          <b><%= sub_para.title %></b>
        </div>
        <div class="card-body">
        <%= sub_para.content %>
        </div>
      </div>
    <% end %>
  </div>
  <!-- /.card-body -->

</div>
<!-- /.card -->

app/views/paragraphs/_sub_paragraph.html.erb
<%= content_tag :div, class: "nested-fields", data: { new_record: form.object.new_record? } do %>

  <div class="card">

    <div class="card-header">
      <% if action_name == "new" %>
        Sous-paragraphe du nouvel élément
      <% else %>
        Sous-paragraphe de <b><%= @paragraph.title %></b>
      <% end %>
      <%= link_to "#", data: { action: "click->nested-form#remove_association" }, class: "float-right" do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </div>

    <div class="card-body">
      <div class="form-group">
        <%= form.input :title, label: false %>
      </div>
      <div class="form-group">
        <%= form.input :content, as: :rich_text_area, placeholder: 'Ecrivez votre paragraphe ici', class: 'form-control', label: false %>
      </div>
      <%= form.input :_destroy, as: :hidden %>
    </div>

  </div>

<% end %>

app/views/paragraphs/destroy.js.erb
$(".delete").bind('ajax:success', function() {
  $(this).closest('.to_delete').fadeOut();
})

app/views/paragraphs/index.html.erb
<div class="content-header">
  <div class="row mb-2">
    <div class="col-sm-6 offset-6">
      <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active">Paragraphes</li>
      </ol>
    </div><!-- /.col -->
  </div><!-- /.row -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">
  <div class="jumbotron">
    <h2>Liste des paragraphes</h2>
  </div>
  <div class="card">
    <div class="card-body">
      <div data-controller="drag" data-drag-url="/paragraphs/:id/move" id="paragraphs">
        <%= render @paragraphs.ordered_by_position %>
      </div>
      <div class="float-right" id="new-paragraph">
        <%= link_to "Nouveau Paragraphe", new_paragraph_path, remote: true, class: "btn btn-dark" %>
      </div>
    </div>
  </div>
</section>

app/views/scenarios/_scenario.html.erb
<div class="row to_delete mb-30">

  <div class="col-sm-4 mb-3 mb-md-0" id="scenario_<%= scenario.id %>">
    <p><%= scenario.description %></p>
    <p class="delete">
      <span>
        <%= link_to edit_scenario_path(scenario, ticket_id: @ticket.id), remote: true do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </span>
      <span>
        <%= link_to scenario_path(scenario, ticket_id: @ticket.id), method: :delete, data: {confirm: "Etes-vous sur", remote: true } do %>
          <i class="fas fa-trash"></i>
        <% end %>
      </span>
    </p>
  </div>

  <div class="col-sm-8">
    <% scenario.results.each do |result| %>
      <div class="row">
        <div class="col-sm-8">
          <%= result.description %>
        </div>
        <div class="col-sm-2">
          <%= result.dev %>
        </div>
        <div class="col-sm-2">
          <%= result.staging %>
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/scenarios/index.html.erb
<div class="content-header">
  <div class="row mb-2">

    <div class="col-sm-6 offset-6">
      <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="#">Home</a></li>
        <li class="breadcrumb-item active">Tickets</li>
      </ol>
    </div><!-- /.col -->
  </div><!-- /.row -->
</div>
<!-- /.content-header -->

<!-- Main content -->
<section class="content">

  <div class="jumbotron">
    <h2><%= @ticket.title %></h2>
    <h4><%= @ticket.url_link %></h4>
  </div>

  <div class="card">
    <div class="card-header">
      <p class="text-center"><b>Ticket <%= @ticket.issue_id %></b></p>
      <p><%= @ticket.tracker %> <%= @ticket.issue_id %> | <%= @ticket.description %></p>
      <p><%= @ticket.url_link %></p>
    </div>

    <div class="card-body">
      <div id="scenarios">
        <div class="row header-black mb-30">
          <div class="col-sm-4">
            <h5>Action</h5>
          </div>
          <div class="col-sm-8">
            <div class="row">
              <div class="col-sm-8">
                <h5>Attendus</h5>
              </div>
              <div class="col-sm-2">
                <h5>Dev</h5>
              </div>
              <div class="col-sm-2">
                <h5>Staging</h5>
              </div>
            </div>
          </div>
        </div>
        <%= render @scenarios %>
      </div>
    </div>
    <!-- /.card-body -->
    <div class="card-footer">
      <div class="float-right" id="new-scenario">
        <%= link_to "Nouveau scénario", new_scenario_path(ticket_id: @ticket.id), remote: true, class: "btn btn-dark" %>
      </div>
    </div>
    <!-- /.card-footer-->
  </div>
  <!-- /.card -->

  <div class="row" id="commentaire">
    <div class="col-sm-12">
      <%= simple_form_for @ticket, :url => update_comment_path(ticket_id: @ticket.id) do |f| %>
        <div class="card">
          <div class="card-body">
            <h4>Commentaire</h4>
            <div class="form-inputs">
              <%= f.input :comment, as: :text %>
            </div>
            <div class="form-actions">
              <%= f.button :submit, "Mettre à jour", class: "btn btn-primary" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

</section>

app/views/tickets/_ticket.html.erb
<!-- Default box -->
<div class="card" data-id="<%= ticket.id %>">

  <div class="card-header text-center">
    <i class="fas fa-grip-vertical grip text-secondary float-left"></i>
    <b>Ticket <%= ticket.issue_id %></b>
  </div>

  <div class="card-header">
    <span class="badge badge-primary"><%= ticket.tracker %> <%= ticket.issue_id %></span> | <b><%= ticket.title %></b>
    <div class="card-tools">
      <span><a href="<%= edit_ticket_path(ticket.id) %>" class="btn btn-tool">Editer</a></span>
      <span><a href="<%= ticket_path(ticket.id) %>" class="btn btn-tool" data-confirm="Etes-vous sur?" data-method="DELETE">Supprimer</a></span>
    </div>
  </div>

  <div class="card-body">
    <%= ticket.description %>
  </div>
  <!-- /.card-body -->
  <div class="card-footer">
    <%= link_to "Voir les tests", scenarios_path(ticket_id: ticket.id), class: "btn btn-sm btn-info float-right" %>
  </div>
  <!-- /.card-footer-->
</div>
<!-- /.card -->